name: Déploiement FTP sur Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    environment: kayak
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/weclain.com/public_html/kayak/
          exclude: |
            **/.git*
            **/.git*/**
            **/.env
            **/cache/**
